#!/bin/bash

# Claude API Orchestrator - Demo Script
# Shows how the orchestrator works without requiring an API key

echo "================================================"
echo "Claude API Orchestrator - Demo Mode"
echo "================================================"
echo ""
echo "This demo shows how the orchestrator would work:"
echo ""
echo "1. VOICE INPUT:"
echo "   🎤 'Create a Python web scraper for Amazon prices'"
echo ""
echo "2. CLAUDE API PLANNING:"
echo "   📋 Breaking down into tasks:"
echo "   - Create project structure"
echo "   - Implement scraper module"
echo "   - Add price monitoring"
echo "   - Set up notifications"
echo ""
echo "3. CLAUDE CODE EXECUTION:"
echo "   🔧 Running each task through Claude Code"
echo "   ✓ Created: scraper.py"
echo "   ✓ Created: monitor.py"
echo "   ✓ Created: config.json"
echo ""
echo "4. CHECKPOINT:"
echo "   🛑 Review point - Continue? [y/n]"
echo ""
echo "5. VERIFICATION:"
echo "   🔄 Claude API verifies results"
echo "   ✅ All requirements met!"
echo ""
echo "================================================"
echo "To run the actual orchestrator:"
echo ""
echo "1. Get an API key from https://console.anthropic.com/"
echo "2. Set it: export ANTHROPIC_API_KEY='your-key'"
echo "3. Run: claude-assistant orch 'your request'"
echo "================================================"